<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_04_Pandas Pivot Tables.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [27]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## 🟩 Count Job Postings by Title and Country (2.4.1)

In [ ]:
job_postings = df.pivot_table(index = ['job_title_short','job_country'], aggfunc = 'size').
job_postings.head(10)

job_title_short   job_country
Business Analyst  Afghanistan      4
                  Albania         11
                  Algeria         21
                  Angola           1
                  Argentina      453
                  Armenia         29
                  Australia      928
                  Austria        738
                  Azerbaijan      16
                  Bahamas          5
dtype: int64

---

## 🟨 Salary Stats by Job Title (2.4.2)

In [26]:
table = df.pivot_table(index = 'company_name',
                        values = 'salary_year_avg',
                        aggfunc = ['min', 'max', 'median'])
table.head(5)

                                    min             max          median
                        salary_year_avg salary_year_avg salary_year_avg
company_name
#twiceasnice Recruiting    61000.000000   120000.000000    65000.000000
/dev/color                125000.000000   125000.000000   125000.000000
0nward Select              92500.000000    92500.000000    92500.000000
1 Point System            137290.484375   137290.484375   137290.484375
1 Point System LLC.       170000.000000   170000.000000   170000.000000

---

## 🟥 Sum Salary by Title and Country (2.4.3)

In [31]:
df_only_scientist = df.copy()
df_only_scientist = df[df['job_title_short'] == 'Data Scientist']
df_only_scientist = df_only_scientist.pivot_table(index = ['company_name','job_country'], values = 'salary_year_avg', aggfunc = 'median')
df_only_scientist = df_only_scientist[df_only_scientist['salary_year_avg'] > 200000]
df_only_scientist.head(10)

                                   salary_year_avg
company_name        job_country
ACT                 Sudan                 225000.0
                    United States         225000.0
Abbott              United States         204000.0
Airbnb              United States         212500.0
Airtable            Sudan                 215500.0
                    United States         233500.0
Algo Capital Group  Sudan                 325000.0
                    United States         350000.0
Amadeus Search      United States         232500.0
Analog Devices, Inc United States         375000.0

---